apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: valentine
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    # Domaine nu
    - match: Host(`valentine.dgsynthex.online`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: valentine-service
          port: 80

    # Wildcard
    - match: HostRegexp(`{subdomain:.+}.valentine.dgsynthex.online`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: valentine-service
          port: 80

  tls:
    certResolver: le
    domains:
      - main: valentine.dgsynthex.online
        sans:
          - "*.valentine.dgsynthex.online"
