apiVersion: v1
kind: Service
metadata:
  name: valentine-service
  namespace: apps
spec:
  selector:
    app: valentine
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080