apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: valentine-wildcard
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`{name:[a-z0-9-]+}.valentine.dgsynthex.online`) && PathPrefix(`/api`)
      kind: Rule
      priority: 100
      services:
        - name: valentine-backend
          port: 3000
    - match: HostRegexp(`{name:[a-z0-9-]+}.valentine.dgsynthex.online`)
      kind: Rule
      priority: 1
      services:
        - name: valentine-frontend
          port: 80
  tls:
    certResolver: le_dns
    domains:
      - main: "valentine.dgsynthex.online"
        sans:
          - "*.valentine.dgsynthex.online"
